# You can override the included template(s) by including variable overrides
# See https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#priority-of-environment-variables
stages:
- deploy



pages:
  stage: deploy

  image: "node:14.16.0-alpine3.10"

  script:
  - yarn
  - yarn build
  - yarn export
  - mv out/* public/

  cache:
    paths:
    - node_modules
    - ".next"

  artifacts:
    paths:
    - public
    expire_in: 1 day
  only:
    - main

